name: Deployment Pipeline

on: 
    push:
        branches:
            - main

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run lint